path_classifiers:
  docs:
    - docs
  test:
    - exclude: /
    - tests
  generated:
    - exclude: build
  library:
    - exclude: third-party
  tools:
    - tools
  examples:
    - examples

queries:
  - exclude: "*"
  - include:
      tags:
        - "security"
        - "correctness"
      severity: "error"

extraction:
  cpp:
    prepare:
       packages:
         - build-essential
         - cmake
         - git
         - libaio-dev
         - libcunit1-dev
         - libncurses5-dev
         - libnuma-dev
         - libssl-dev
         - nasm
         - uuid-dev
    after_prepare:
      - export GNU_MAKE=make
      - export GIT=true
    configure:
      command:
        - ./configure
    index:
      build_command:
        - $GNU_MAKE -j2
      all_solutions: false
      nuget_restore: false
