name: testing

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

defaults:
  run:
    shell: bash -l {0}

jobs:

  vroom:

    runs-on: self-hosted
    container:
      image: refenv/qemu-nvme:latest
      options: --privileged

    steps:
    - name: Define stuff
      run: |
        echo "::set-env name=ARTIFACTS::/tmp/artifacts"
        echo "::set-env name=ARTIFACTS_LATEST::/tmp/artifacts/latest"
        echo "::set-env name=RESULTS::/tmp/results"
        echo "::set-env name=RESULTS_LATEST::/tmp/results/latest"
        echo "::set-env name=TARGET_ENV::/opt/envs/localhost-qemu.sh"

    - name: Create result and artifacts directories
      run: |
        mkdir -p ${ARTIFACTS_LATEST}
        mkdir -p ${RESULTS_LATEST}

    - name: Start the SSH server
      run: service ssh restart

    - name: QEMU, provision guest using Debian cloud image
      run: qemu::img_from_url "https://bit.ly/2Dyg4Xd"

    - name: QEMU, start the guest
      run: qemu::run

    - name: CIJOE, invoke the test-runner targeting the qemu-guest
      run: |
        cij_runner \
          $CIJ_TESTPLANS/example_01_usage.plan \
          ${TARGET_ENV} \
          --output ${RESULTS_LATEST}

    - name: QEMU, kill the guest
      run: qemu::kill

    - name: CIJOE, result-log-dump on error
      if: failure()
      run: find ${RESULTS} -name "*.log" | xargs cat

    - name: CIJOE, generate test-report
      if: always()
      run: cij_reporter ${RESULTS_LATEST}

    - name: CIJOE, upload test results and report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: /tmp/results/*
